version: '3'
services:
  
  influxdb:
    image: "influxdb:1.8.1"
    #restart: always
    #volumes:
    #  - /var/influxdb/volume:/var/lib/influxdb
    environment:
      INFLUXDB_DB: "\"loadTests\""
      #estas 3 env variables no son obligatorias, se puede dejar sin credenciales
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "tempUser"
      INFLUXDB_ADMIN_PASSWORD: "tempPass"
    ports:
      - "8086:8086"

  grafana:
    image: "grafana/grafana:7.1.3"
    #restart: always
    #volumes:
    #  - /var/grafana/volume:/var/lib/grafana #si da error de permisos corre esto: sudo chown -R 472:472 /var/grafana/volume
    environment:
      - "GF_SERVER_ROOT_URL=http://grafana:6082"
      #estas 2 var no son necesarias se puede quedar sin credenciales y por defecto son  user:admin pass:admin
      - GF_SECURITY_ADMIN_PASSWORD=newpassword
      - GF_SECURITY_ADMIN_USER=someUser
    ports:
      - "3000:3000"
    depends_on:
      - "influxdb"
      
  #elasticsearch:
  #  image: "elasticsearch:7.8.1"
  #  environment:
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #    - "discovery.type=single-node"
  #  ports:
  #    - "9200:9200"
  #    - "9300:9300"

  #kibana:
  #  image: "kibana:7.8.1"
  #  ports:
  #    - "5601:5601"